### ISSUE TITLE
Two progressors in the same function gives error

### ISSUE THREAD

**Issue by dwachsmuth** [HenrikBengtsson/progressr#105]
I have a package under development which uses progressr extensively in some time-consuming, multistep functions. I have them written with multiple progressor functions, and at some point in the last month or two they have stopped working. Here is a minimal reproducible example, using progressr 0.7.0 on R 4.0.3:

```
library(progressr)

test_fun <- function() {
  
  pb <- progressor(10)
  
  for (i in 1:10) {
    pb()
    Sys.sleep(0.2)
    }
  
  pb <- progressor(10)
  
  for (i in 1:10) {
    pb()
    Sys.sleep(0.2)
    }
}

with_progress(test_fun())
```

The first for loop executes with no problem, but the second one fails with:
```
Error in assign("...progressor", value = fcn, envir = envir) : 
  cannot change value of locked binding for '...progressor' 
``` 

This pattern used to work, but no longer does. Any help would be greatly appreciated!

**Comment by xtimbeau** [comment]
You can use local() to solve this:

```
library(progressr)


test_fun <- function() {
  
  local({
    pb <- progressor(10)
    
    for (i in 1:10) {
      pb()
      Sys.sleep(0.2)
    }
  })
  
  local({
    pb <- progressor(10)
    
    for (i in 1:10) {
      pb()
      Sys.sleep(0.2)
    }
  })
}
with_progress(test_fun())
```

**Comment by HenrikBengtsson** [comment]
Thanks for reporting.  Yes, this new "behavior" was introduced in **progressr** 0.7.0, which was because of the introduction of global progression handlers.  It was needed to protect against mistakes where creating a new progressor with an existing one being active risked breaking the global handler.  I've now relaxed some of this protection for the next release (available in the develop branch), cf. commit 3b1846b5.  

> NEWS:
> ...
> * Creating a new progressor() will now automatically finish an existing
>   progressor in the same environment.  The previous behavior was to give an error

**Comment by HenrikBengtsson** [comment]
FYI, **progressr** 0.8.0 fixing this just reached CRAN.
