### ISSUE TITLE
typo in handler_shiny doc

### ISSUE THREAD

**Issue by gitdemont** [HenrikBengtsson/progressr#137]
Hi @HenrikBengtsson ,

I think there is a typo error [here ](https://github.com/HenrikBengtsson/progressr/blob/c97fbefc73a69c0dade7d77d26151337cb278449/R/handler_shiny.R#L11) `"sticky-message"` should be `"sticky_message"` (and same in corresponding .Rd)

In addition, it would be great to mention what would be the behaviour of using NULL
e.g. with inputs = list(message = NULL, detail = "message") will update the Shiny 'detail' component using any message whereas the 'message' component will never be updated.

**Comment by HenrikBengtsson** [comment]
Thank you. Fixed.
