### ISSUE TITLE
No progressor update on Shiny Server (withProgressShiny)

### ISSUE THREAD

**Issue by wstvcg** [HenrikBengtsson/progressr#150]
If i deploy the minimal example via RStudio Server (rocker/shiny-verse:latest) the progressor  doesn't update the detail, only initiates the message.

On a local machine it works flawlessly. Any advice would be appreciated. Do I need to pass another envir?

```
library(shiny)
library(progressr)
app <- shinyApp(
  ui = fluidPage(
    plotOutput("plot")
  ),
  
  server = function(input, output) {
    output$plot <- renderPlot({
      X <- 1:500
      withProgressShiny(message = "Calculation in progress",
                        detail = "Starting ...",
                        value = 0, {
                          p <- progressor(along = X)
                          y <- lapply(X, FUN=function(x) {
                            Sys.sleep(0.25)
                            p(sprintf("x=%d", x))
                          })
                        })
      
      plot(cars)
    })
  }
)
```

**Comment by HenrikBengtsson** [comment]
Thanks for reporting.  I can reproduce this when deploying to <https://www.shinyapps.io/>.  I've also verified that `shiny::withProgress()` and `shiny::incProgress()` works as expected there, so this appears to be related to **progressr**.  It's odd, but hopefully there's a simple explanation and solution to this.

I'll try to look into this in 2023.

**Comment by HenrikBengtsson** [comment]
Now fixed for the next release, cf. 583ca14.

Thanks for reporting.

**Comment by HenrikBengtsson** [comment]
progressr 0.13.0 is now on CRAN fixing this
