### ISSUE TITLE
Add example: How to use progressr for `knitr.progress.fun`?

### ISSUE THREAD

**Issue by jooyoungseo** [HenrikBengtsson/progressr#154]
[knitr v1.42](https://github.com/yihui/knitr/releases/tag/v1.42) has introduced a new `knitr.progress.fun` option. It would be great if a description could be added explaining how {progressr} functions can be used for this new knitr option.

**Comment by HenrikBengtsson** [comment]
I added <https://progressr.futureverse.org/#the-knitr-package> at the end of last year.  Is that what you're looking for?

**Comment by jooyoungseo** [comment]
Aw, I did not know that the description had already existed. Yes, just like that! Thank you very much! Please feel free to close this issue.
