### ISSUE TITLE
DESIGN: Value of with_progress()?

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/progressr#26]
Currently `with_progress(expr)` returns the value of `expr`, which allows us to do either:
```r
with_progress(y <- slow_sum(x))
```
or
```r
y <- with_progress(slow_sum(x))
```

However, if we restrict ourselves to the first case, then we can have `with_progress()` return other things, e.g.
```r
progress_summary <- with_progress(y <- slow_sum(x))
```
The question is if that is useful beyond debugging/troubleshooting.

**Comment by s-fleck** [comment]
I think with_progress should return the value of expr to be consistent with `with()` and the various `with_*` functions from withr.

Maybe one could make the last progress summary available via something like `.last_progress_summary`, in line with `.Last.value` or `rhub::rhub::last_check()` and `rlang::last_error()` etc...

**Comment by HenrikBengtsson** [comment]
I certainly lean toward having `with_progress()` return the value of the expression.

Where/how to transfer progress stats/logs is less clear.  Per CRAN policies we're not really allowed to store anything in user's `globalenv()`.  OTH, I'm not sure there's a policy on saving to the `parent.frame()`.  Anyway, it's also a matter style and adding yet another hidden return value. There's also the approach that `withVisible()` takes - returning a list.  It might also be that progress logs/stats can be taken care of by a specific handler.

Also, hopefully, we'll be getting support for global calling handlers in R soon, which removes the need for `with_progress()`.  That will also affect where we going in this question.  I'll let it all mature together for a while - hopefully, a good, natural solution will appear from this.

**Comment by s-fleck** [comment]
assigning to the global environment is a nono, but you can assign to an environment inside your package namespace and then have a function to retrieve that value. Still not very good practice, except for some very special use cases [example(https://github.com/s-fleck/hammr/blob/master/R/ticktock.R)].

What about something like:

```
with_progress({
  slow_sum(1:10)
  get_current_progress_summary()
})

# or 

with_progress({
  slow_sum(1:10)
}, summary = TRUE)
```
(just thinking out loudly here, no need to comment ;) )

I'm also not sure that global calling handlers would make `with_progress()` obsolete, `with()` style functions are exactly useful *because* they let you temporarily modify global behavior without lasting side effects.

**Comment by HenrikBengtsson** [comment]
we're on the same page

**Comment by HenrikBengtsson** [comment]
@DavisVaughan brought up a good argument in Issue #85 for having `with_progress(expr)` return the value of `expr`, namely using it _within_ a magrittr pipeline, e.g.
```r
t <- df %>% mutate(x = with_progress(future_map(data, nrow))) %>% something_more
```
I anticipated it to be used as:
```r
with_progress({
  y <- df %>% mutate(x = future_map(data, nrow)) %>% something_more
})
```
but I can see that there is a need for the first version.  So, this adds another reason for having `with_progress()` return the value of the expression.  I'll try to give some more thought and, hopefully, we can make the move.

**Comment by HenrikBengtsson** [comment]
Now `y <- with_expression(expr)` works.

**Comment by DavisVaughan** [comment]
I think your commit means that #86 can be closed. There are a few tests there you may want to pull in

**Comment by HenrikBengtsson** [comment]
Oh.  Thxs, I'm still haven't learned to look at the PR tab.  I'll make sure to bring in those tests.
