### ISSUE TITLE
Terminology: intrusiveness or obtrusiveness?

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/progressr#61]

**Comment by Bisaloo** [comment]
As a non-native speaker (French), intrusiveness sounds a bit easier but could you share the context please?

**Comment by HenrikBengtsson** [comment]
Thxs.  Same here (Swedish) - more familiar with the term 'intrusive' than 'obtrusive'.  This is meant for an argument, currently, named 'intrusiveness', which is a scale factor that controls how "intrusive" a type of progress update reporter/hander is.   For instance, a progress bar in the terminal is considered to have 'intrusiveness=1.0' whereas sound updates via is considered more disturbing so the beepr handler gets 'intrusiveness=10.0'.  This scale factor basically controls how frequent the progress is reported/updated to the end-user.

Maybe there's a better term than either of these two.

**Comment by mike-lawrence** [comment]
Intrusive is a higher frequency word in English than obtrusive; even as an english speaker I had to look up obtrusive. Another alternative is to invert the meaning of the argument and call it "niceness", a term familiar to unix users (though maybe too familiar and connoting too strongly process priority?).

**Comment by HenrikBengtsson** [comment]
Thanks for the feedback. I'll stick with `intrusiveness`; willing to change if it turns out to be confusing or there's pushback but I guess it's unlikely since it's an argument that is unlikely to be used by most people
