### ISSUE TITLE
Handler naming scheme

### ISSUE THREAD

**Issue by DavisVaughan** [HenrikBengtsson/progressr#65]
Would it look any cleaner to have:

```
handler_ascii_alert()
handler_beepr()
handler_debug()
...
```

rather than:

```
beepr_handler()
ascii_alert_handler()
debug_handler()
```

It would play nicely with autocomplete and I think it groups them together well.

**Comment by HenrikBengtsson** [comment]
I agree, this is neater for autocompletion.  I've been holding back on making these changes in case I could come up with a better name than "handler", cf. Issue #32.  The term "handler" stems from the fact that they serve as calling handlers (as in `base::withCallingHandlers()`) internally.

**Comment by HenrikBengtsson** [comment]
Done.
