### ISSUE TITLE
Support for crayon styling in progress bar output

### ISSUE THREAD

**Issue by dwachsmuth** [HenrikBengtsson/progressr#76]
As far as I can tell, progressr doesn't support using crayon styling to change the colour or weight of terminal output. This came up when I attempted to replicate a previous progress::progress_bar format using handler_progress().

So the following produces silver text:

`pb <-`
`  progress::progress_bar$new(`
`    format = crayon::silver(":current of :total [:bar]"), `
`    total = 5`
`    )`

`for (i in 1:5) {`
`  pb$tick()`
`  Sys.sleep(1)  `
`}`

But the following does not produce styled text, even though it otherwise seems to support the `format` argument of progress::progress_bar. (It also doesn't thrown an error or warning that the crayon formatting is being ignored.)

`with_progress({`
  
`  pb <- progressor(steps = 5)`
  
`  for (i in 1:5) {`
`    pb()`
`    Sys.sleep(1)`
`    }`
`  }, `
`  handlers = handler_progress(`
`    format = crayon::silver(":current of :total [:bar]")`
`    ))`

Is there another way to apply terminal styling to progress bar output that I am missing? If not, is this a feature you'd consider supporting?

**Comment by HenrikBengtsson** [comment]
You're almost there; the following does what you want.

```r
library(progressr)

## The user specifies which progress handler(s) to use
handlers(handler_progress(format = crayon::silver(":spin [:bar] :percent :message")))

## The these handler(s) are used whenever with_progress() is in place
with_progress({
  pb <- progressor(steps = 5)
  for (i in 1:5) {
    pb()
    Sys.sleep(1)
  }
})
```

**Comment by dwachsmuth** [comment]
Hi Henrik,

Thanks for the reply, but I don’t think it addresses my issue, which is that the output styling from the crayon package isn’t applied in progressr, regardless of whether it is specified in the handler_progress format argument.

At least on my machine, when I run the code you sent me, the progress bar is NOT drawn in the colour specified by crayon::silver(), but instead remains in the default styling.

This is in contrast to the progress package, where the exact same format argument will draw the progress bar in silver text.

Please let me know if that clarifies the issue.


—

David Wachsmuth
Canada Research Chair in Urban Governance

Assistant Professor, School of Urban Planning
Associate Member, Department of Geography
McGill University

Early Career Editor
Territory, Politics, Governance

Macdonald-Harrington Building, Room 405
815 Sherbrooke Street West<x-apple-data-detectors://2>
Montreal QC H3A 0C2<x-apple-data-detectors://2>

514-398-4078<tel:514-398-4078>, david.wachsmuth@mcgill.ca<mailto:david.wachsmuth@mcgill.ca>,
upgo.lab.mcgill.ca<http://upgo.lab.mcgill.ca/>, github.com/UPGo-McGill<http://github.com/UPGo-McGill>

On Apr 27, 2020, at 17:47, Henrik Bengtsson <notifications@github.com> wrote:

﻿

You're almost there; the following does what you want.

library(progressr)

## The user specifies which progress handler(s) to use
handlers(handler_progress(format = crayon::silver(":spin [:bar] :percent :message")))

## The these handler(s) are used whenever with_progress() is in place
with_progress({
  pb <- progressor(steps = 5)
  for (i in 1:5) {
    pb()
    Sys.sleep(1)
  }
})

**Comment by HenrikBengtsson** [comment]
Aha... I been very puzzled for the last 20 minutes, because "it works for me".  However, eventually, I tried with `R --vanilla` (which comes to rescue in many cases), and then I could reproduce.  Turns out I have:
```r
if (crayon:::has_color()) options(crayon.enabled = TRUE)
```
in my `~/.Rprofile` set up.  This makes it work.  Without, it doesn't.  The reason is explained in https://github.com/r-lib/crayon/issues/48 (... and of course, it was me that had this problem in the past but for a completely different reason).

So, for now, as a workaround, use:
```r
library(progressr)
if (crayon:::has_color()) options(crayon.enabled = TRUE)
handlers(handler_progress(format = crayon::red(":current of :total [:bar]")))
```

I'll see if I can apply this "workaround" to the internal code of `handler_progress()`.

```

**Comment by HenrikBengtsson** [comment]
Here's an easier workaround - wrapping the `format` argument in `as.character()` will do it, e.g.

```r
library(progressr)
handlers(handler_progress(format = as.character(crayon::red(":current of :total [:bar]"))))
with_progress(slow_sum(1:5))
```

**Comment by HenrikBengtsson** [comment]
This has been fixed for the next release.  Until then, install as:
```r
remotes::install_github("HenrikBengtsson/progressr@develop")
```

Thanks for inquiring/reporting.

**Comment by dwachsmuth** [comment]
Thanks very much for the quick action on this! I’ve been very excited to see the progressr package develop.


—

David Wachsmuth
Canada Research Chair in Urban Governance

Assistant Professor, School of Urban Planning
Associate Member, Department of Geography
McGill University

Early Career Editor
Territory, Politics, Governance

Macdonald-Harrington Building, Room 405
815 Sherbrooke Street West<x-apple-data-detectors://2>
Montreal QC H3A 0C2<x-apple-data-detectors://2>

514-398-4078<tel:514-398-4078>, david.wachsmuth@mcgill.ca<mailto:david.wachsmuth@mcgill.ca>,
upgo.lab.mcgill.ca<http://upgo.lab.mcgill.ca/>, github.com/UPGo-McGill<http://github.com/UPGo-McGill>

On Apr 27, 2020, at 22:02, Henrik Bengtsson <notifications@github.com> wrote:

﻿

This has been fixed for the next release. Until then, install as:

remotes::install_github("HenrikBengtsson/progressr@develop")

Thanks for inquiring/reporting.

**Comment by HenrikBengtsson** [comment]
:) ... only possible with feedback like yours

**Comment by HenrikBengtsson** [comment]
progressr 0.6.0 on CRAN just now.

**Comment by dwachsmuth** [comment]
I just installed progressr 0.6.0, and can confirm that crayon styling is working "out of the box" without needing to set the crayon.enabled option. Thanks again!
