### ISSUE TITLE
pass parameters to progress::progress_bar constructor

### ISSUE THREAD

**Issue by yimyom** [HenrikBengtsson/progressr#82]
Hi,

I'm not sure if I missed something _obvious_ in the API or if it's missing so I prefer to ask for help. I'd like to pass more parameters to the constructor of `progress_bar`, in particular the parameter `width`. But if I look into `handler_progress`, the variable `reporter` defines a function `make_pb` which calls the `progress_bar`. When `make_pb` is called, only the explicitely defined parameters in `handler_progress` are passed to the constructor. If they're not defined, .... well... they're not passed in this implementation.
Ultimately, I just wanted to define the `width` of my progress bar. :-D

Cheers,
David

**Comment by HenrikBengtsson** [comment]
As a started, I've added support for controlling the `width`.  

I need to figure out a more general way to pass on arguments to the individual progress backends to avoid having to update this package every time one of the backends adds or removes an argument.

**Comment by HenrikBengtsson** [comment]
Found a much better solution.  Any arguments in `...` that is not defined/used locally are passed on to the progress-handler backend, e.g.

```r
handlers(list(
  handler_progress(width = 40, complete = "+"),
  handler_beepr(finish = 9)
))
```

This is available in the 'develop' branch and part of the next release.

**Comment by yimyom** [comment]
Henrik, you're just awesome. Thansk for the fix. And nice idea to parse `...` for unknown arguments.

**Comment by HenrikBengtsson** [comment]
progressr 0.6.0 on CRAN just now.

**Comment by yimyom** [comment]
Awesome!
Thanks
