### ISSUE TITLE
Non fixed steps

### ISSUE THREAD

**Issue by xtimbeau** [HenrikBengtsson/progressr#97]
Is it possible to track progress with a variable amount of progress completed?
One way to implement it could be trhough the progressor function call.
it would look like:
pb() <- progressor(steps=1000)

and then the call to pb() would pass the amount done (current behavior being done=1)

pb(done=5) # 5 steps out of 1000 accomplished 
...
p￼b(done=10) # 10 this time

it could be also a negative progress for some bizarre cases.

**Comment by HenrikBengtsson** [comment]
There's an _open_ issue #21 regarding negative progress

**Comment by xtimbeau** [comment]
great, I missed that in the doc!

Le mer. 2 déc. 2020 à 15:36, Henrik Bengtsson <notifications@github.com> a
écrit :
