### ISSUE TITLE
Keep progress bars from disappearing after completion

### ISSUE THREAD

**Issue by mattwarkentin** [HenrikBengtsson/progressr#98]
Hi @HenrikBengtsson,

Would you consider adding the ability to keep a progress bar from disappearing after completion? Personally, I use `handler_progress()` to construct my progress bars, and `progress` has it's own argument to control whether the bar is cleared:
```r
progress::progress_bar$new(clear = FALSE)
```

Would you consider adding an argument to `handler_progress()` to control this behaviour? Or better yet, support passing several arguments to `progress::progress_bar` to control this behaviour but also for finer control over things like appearance, such as the characters used for `complete`, `incomplete`, and `current`.

Right now with `handler_progress()` you can control the general `progress` bar format, but not the lower-level aesthetics.

Thanks for the awesome package!

**Comment by HenrikBengtsson** [comment]
Hi. Two options; either set it for each handler specifically:

```r
handlers(handler_progress(clear = FALSE))
```

or "globally" for all handlers:

```
options(progressr.clear = FALSE)
```

**Comment by HenrikBengtsson** [comment]
You can pass down those other **progress** arguments too, e.g.

```r
> handlers(handler_progress(incomplete=".", complete="*", current="o"))
> with_progress(slow_sum(1:3))
M: Added value 1                                       
[***********o........................]  33% P: Adding 1
```

**Comment by mattwarkentin** [comment]
Ah yes. I now see that the dots in `handler_progress()` can include `clear` which is passed on to `make_progression_handler()`. Thanks for the response.

Regarding the other `progress` arguments - maybe the documentation for `make_progress_handler()` needs to be updated? The `...` indicate they are passed to themself (infinite recursion), but it seems like they are passed on the to back-end.

**Comment by HenrikBengtsson** [comment]
> Regarding the other progress arguments - maybe the documentation for make_progress_handler() needs to be updated? The ... indicate they are passed to themself (infinite recursion), but it seems like they are passed on the to back-end.

Yeah, there's much more to do on the help in this package (hence the 'lifecycle:experimental' badge).  Also, when we roll out global progression handlers (https://github.com/HenrikBengtsson/progressr/issues/95), a lot of things will change how people are going to use the package, so no point in updating docs prior to that.  (Don't worry, it'll be backward compatible).

**Comment by mattwarkentin** [comment]
Sounds good! I am excited about the idea of global handlers. My basic understanding is that simply registering handlers with `handlers()` will start the listening without the need for `with_progress()`. Is that circling on correct?

**Comment by HenrikBengtsson** [comment]
Yup, that's correct.
